[package]
name = "umix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cranelift = "0.108.1"
cranelift-jit = "0.108.1"
cranelift-module = "0.108.1"
cranelift-native = "0.108.1"
strum = { version = "0.26", features = ["derive"] }
